FROM python:3.11-slim

# System deps (gcc needed for some torch/numpy builds)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python deps first (layer-cached if requirements.txt unchanged)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY backend/ ./backend/
COPY scripts/ ./scripts/

# Copy pre-trained model weights
# (generated by scripts/train.py — must be present before building)
COPY backend/models/saved/ ./backend/models/saved/
COPY backend/data/processed/ ./backend/data/processed/

EXPOSE 8000

CMD ["uvicorn", "backend.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
